name: proyek_uts
description: Project UAS Flutter bertema Aplikasi Quran.
# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Pastikan versi SDK Flutter Anda didukung

dependencies:
  flutter:
    sdk: flutter

  # Dependency yang Anda pilih (Persyaratan d)
  quran_library: ^2.3.1
  
  # Ikon bawaan
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter untuk analisis kode
  flutter_lints: ^3.0.0

# Bagian konfigurasi spesifik Flutter (JANGAN DIUBAH INDENTASINYA!)
flutter:
  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true

assets:
   - images/
   - images/a_dot_burr.jpeg
  
fonts:
   - family: Scherezade
     fonts:
      - asset: fonts/Scheherazade-Regular.ttf
      - asset: fonts/Scheherazade-Bold.ttf
        weight: 700